eureka:
  instance:
    hostname: licensingservice
    preferIpAddress: false
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
